# 鼠标单击特效 当前为：烟花
fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: false

# 404页面
error_404:
  enable: true
  subtitle: "页面没有找到"
  background: 


#导航栏
nav:
  logo: 
  display_title: true
  fixed: false # fixed navigation bar    
post_asset_folder: true  
menu:
  主页: / || fas fa-home
  博文 || fa fa-graduation-cap:
    分类: /categories/ || fa fa-archive
    标签: /tags/ || fa fa-tags
    归档: /archives/ || fa fa-folder-open
  生活 || fas fa-list:
    分享: /shuoshuo/ || fa fa-comments-o
    相册: /photos/ || fa fa-camera-retro
    音乐: /music/ || fa fa-music
    影视: /movies/ || fas fa-video
  友链: /links/ || fa fa-link
  留言板: /comment/ || fa fa-paper-plane
  #留言板: /messageboard/ || fa fa-paper-plane
  关于笔者: /about/ || fas fa-heart  

# #头像
avatar:
  img: ./img/avatar.jpg
  # effect: true # 头像会一直转，转的贼快，太鬼畜了

# Image (圖片設置)
# --------------------------------------

# The banner image of home page
index_img: transparent

# Beautify/Effect (美化/效果)
# --------------------------------------

# The height of top_img, eg: 300px/300em/300rem (主頁top_img高度)
index_top_img_height: 400px

# Website Background (設置網站背景)
# can set it to color or image (可設置圖片 或者 顔色)
# The formal of image: url(http://xxxxxx.com/xxx.jpg)
background: url(/interview_note/img/bg.png)

# Footer Background
footer_bg: transparent

# Add mask to header or footer (为 header 或 footer 添加黑色半透遮罩)
mask:
  header: false

# footer_bg: false

# # 网站运行时间
runtimeshow:
  enable: true
  publish_date: 2/7/2024 15:00:00

inject:  
  head:
    - <link rel="stylesheet" href="./css/transpancy.css">
  bottom:  
     - <script src="./js/sakura.js"></script>
    #- <script src="https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/sakura.js"></script>